name: Deployment - Main Branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1

      - name: Install dependencies
        run: |
          poetry install

      - name: Run linters
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run robot-tests

      - name: Prepare artifact structure for robotframework report
        if: always()
        continue-on-error: true
        run: |
          mkdir -p temp-artifact/reports
          cp -R reports/* temp-artifact/reports

      - name: Upload artifact for 10 days
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: temp-artifact/
          retention-days: 30

      - name: Deploy robotframework report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports
